import Image from "next/image";
import Link from "next/link";
import type { ComponentType } from "react";
import { ArrowRight, BookOpen, CalendarDays, Clock3, HandHeart, HeartHandshake, MapPin, MessageCircle, School, Sparkles, SunMedium, Users } from "lucide-react";

const atividades = [
  { icon: HeartHandshake, titulo: "Atendimento espiritual", texto: "Acolhimento, orientação, passes, corrente de cura e evangelização em um ambiente de paz.", detalhe: "Domingos, das 14h às 18h" },
  { icon: HandHeart, titulo: "Projetos sociais", texto: "Iniciativas que transformam cuidado em ação, apoiando famílias e comunidades da nossa região.", detalhe: "Caridade em movimento" },
  { icon: School, titulo: "Escolas e formação", texto: "Espaços de estudo, desenvolvimento mediúnico e formação para crianças, jovens e adultos.", detalhe: "Aprender para servir melhor" },
];

const agenda = [
  { dia: "DOM", hora: "10h", titulo: "Missa Cristã", nota: "Primeiro domingo do mês" },
  { dia: "DOM", hora: "15h", titulo: "Atendimento público", nota: "Palestra, passes e sopa fraterna" },
  { dia: "SÁB", hora: "15h", titulo: "Desenvolvimento mediúnico", nota: "Estudo e prática responsável" },
];

export default function HomePage() {
  return <div className="min-h-screen overflow-hidden bg-[#f7f4ed] text-[#173f59]">
    <header className="absolute inset-x-0 top-0 z-30 border-b border-white/20 bg-[#082f49]/15 text-white backdrop-blur-md">
      <div className="mx-auto flex h-24 max-w-7xl items-center justify-between px-5 sm:px-8">
        <Link href="/" className="flex items-center gap-3" aria-label="C.E.L.C — Página inicial">
          <span className="grid size-14 place-items-center rounded-full bg-white/95 shadow-lg"><Image src="/celc-logo.png" alt="Símbolo da C.E.L.C" width={32} height={49} priority /></span>
          <span><strong className="block font-serif text-2xl leading-none tracking-[.14em]">C.E.L.C</strong><span className="mt-1 hidden text-[10px] uppercase tracking-[.18em] text-white/80 sm:block">Casa Espiritualista Luz do Caminho</span></span>
        </Link>
        <nav className="hidden items-center gap-7 text-sm font-medium lg:flex" aria-label="Navegação principal">
          <a href="#a-casa" className="hover:text-[#f5c95b]">A Casa</a><a href="#atividades" className="hover:text-[#f5c95b]">Atendimentos</a><a href="#agenda" className="hover:text-[#f5c95b]">Agenda</a><a href="#projetos" className="hover:text-[#f5c95b]">Projetos sociais</a><Link href="/produtos" className="hover:text-[#f5c95b]">Livraria</Link><a href="#contato" className="rounded-full border border-white/35 px-5 py-2.5 hover:bg-white hover:text-[#0b4b70]">Como chegar</a>
        </nav>
        <a href="#agenda" className="rounded-full border border-white/30 px-4 py-2 text-sm font-semibold lg:hidden">Agenda</a>
      </div>
    </header>

    <main>
      <section className="relative flex min-h-[780px] items-end bg-[#083754] pb-16 pt-36 sm:items-center sm:pb-0">
        <Image src="/celc-hero.jpg" alt="Mar ao amanhecer, símbolo de serenidade e renovação" fill priority className="object-cover" sizes="100vw" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,37,57,.93)_0%,rgba(5,45,70,.7)_47%,rgba(5,45,70,.12)_100%)]" />
        <div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(4,37,57,.55),transparent_55%)]" />
        <div className="relative mx-auto w-full max-w-7xl px-5 sm:px-8"><div className="max-w-3xl text-white">
          <div className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[.28em] text-[#f5c95b]"><span className="h-px w-12 bg-[#f5c95b]" />Desde 1977, uma casa para todos</div>
          <h1 className="font-serif text-5xl leading-[1.03] tracking-[-.03em] sm:text-6xl lg:text-[5.25rem]">Um caminho de luz, <em className="font-normal text-[#f7d878]">acolhimento</em> e transformação.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/80 sm:text-xl">Fé, conhecimento e caridade unidos para o desenvolvimento espiritual e o bem-estar de cada pessoa.</p>
          <div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#atividades" className="group inline-flex items-center justify-center gap-2 rounded-full bg-[#f2c34f] px-7 py-4 font-bold text-[#123b52] shadow-xl transition hover:-translate-y-0.5 hover:bg-[#f8d776]">Conheça nossos atendimentos <ArrowRight className="size-4 group-hover:translate-x-1" /></a><a href="#contato" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/40 bg-white/10 px-7 py-4 font-bold backdrop-blur hover:bg-white hover:text-[#123b52]"><MapPin className="size-4" />Visite a C.E.L.C</a></div>
        </div></div>
        <div className="absolute bottom-0 right-0 hidden w-[37%] border-t border-l border-white/20 bg-[#073550]/70 px-8 py-6 text-white backdrop-blur-md xl:block"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-full bg-white/10"><SunMedium className="size-5 text-[#f5c95b]" /></span><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f5c95b]">Próximo encontro</p><p className="mt-1 font-serif text-xl">Domingo, às 15h</p></div></div></div>
      </section>

      <section id="a-casa" className="relative py-24 sm:py-32"><div className="absolute -right-36 top-0 size-[420px] rounded-full bg-[#efc75e]/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">Nossa essência</p><h2 className="section-title mt-5">Uma casa feita de presença, escuta e serviço.</h2></div><div className="border-l border-[#d8cda9] pl-7 sm:pl-10"><p className="text-xl leading-9 text-[#456372]">A Casa Espiritualista Luz do Caminho é uma instituição religiosa e assistencial que pratica o bem de todas as formas, promovendo a caridade e o desenvolvimento intelectual, emocional e espiritual.</p><p className="mt-8 font-serif text-2xl italic text-[#0b5277]">“Trabalho e concórdia a todo custo!”</p></div></div></section>

      <section id="atividades" className="bg-[#0a4668] py-24 text-white sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow gold">Cuidado integral</p><h2 className="mt-5 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Há muitas formas de encontrar o seu caminho.</h2></div><p className="max-w-md leading-7 text-white/70">Nossos trabalhos acolhem quem busca assistência espiritual e quem deseja viver sua religiosidade em comunidade.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] bg-white/15 lg:grid-cols-3">
        {atividades.map(({icon: Icon,titulo,texto,detalhe},index)=><article key={titulo} className="group relative bg-[#0a4668] p-8 hover:bg-[#0d5279] sm:p-10"><span className="absolute right-7 top-7 font-serif text-5xl text-white/10">0{index+1}</span><span className="grid size-14 place-items-center rounded-2xl bg-[#f4ce6a] text-[#16445d]"><Icon className="size-6" /></span><h3 className="mt-8 font-serif text-2xl">{titulo}</h3><p className="mt-4 min-h-24 leading-7 text-white/70">{texto}</p><p className="mt-7 flex items-center gap-2 text-sm font-bold text-[#f4ce6a]"><Sparkles className="size-4" />{detalhe}</p></article>)}
      </div></div></section>

      <section id="agenda" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Encontros</p><h2 className="section-title mt-5">Nossa agenda semanal.</h2><p className="mt-6 max-w-sm leading-7 text-[#58717d]">Chegue como você está. Nossa equipe estará pronta para orientar você na chegada.</p><a href="#contato" className="mt-8 inline-flex items-center gap-2 font-bold text-[#0b5277] hover:underline">Ver localização <ArrowRight className="size-4" /></a></div><div className="divide-y divide-[#d9d1bb] border-y border-[#d9d1bb]">
        {agenda.map(item=><article key={item.titulo} className="grid grid-cols-[74px_1fr] gap-5 py-7 sm:grid-cols-[90px_90px_1fr_auto] sm:items-center"><div className="grid size-16 place-items-center rounded-2xl bg-[#e8efe9] text-xs font-black tracking-[.15em] text-[#0b5277]">{item.dia}</div><p className="font-serif text-2xl text-[#b07c15] sm:text-3xl">{item.hora}</p><div className="col-start-2 sm:col-start-auto"><h3 className="font-serif text-xl sm:text-2xl">{item.titulo}</h3><p className="mt-1 text-sm text-[#6c7d84]">{item.nota}</p></div><CalendarDays className="hidden size-5 text-[#9aabac] sm:block" /></article>)}
      </div></div></div></section>

      <section id="projetos" className="mx-4 overflow-hidden rounded-[2.5rem] bg-[#e6ede6] sm:mx-8 lg:mx-auto lg:max-w-[calc(100%-4rem)]"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="relative min-h-[420px] bg-[#174f69] p-8 text-white sm:p-14"><div className="absolute right-0 top-0 size-64 rounded-full bg-[#f4ce6a]/15 blur-3xl" /><p className="eyebrow gold relative">Caridade que aproxima</p><h2 className="relative mt-6 max-w-lg font-serif text-4xl leading-tight sm:text-5xl">Quando a luz encontra propósito, ela se multiplica.</h2><p className="relative mt-6 max-w-lg leading-7 text-white/70">Nossos projetos sociais criam redes de apoio, educação e dignidade. Toda ajuda se transforma em presença na vida de alguém.</p><a href="#contato" className="relative mt-9 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-bold text-[#16445d] hover:bg-[#f4ce6a]">Quero contribuir <HandHeart className="size-4" /></a></div><div className="grid content-center gap-5 p-8 sm:p-14"><Feature icon={Users} title="Assistência às famílias" text="Acolhimento e suporte para quem mais precisa." /><Feature icon={School} title="Educação e futuro" text="Aprendizado como ferramenta de transformação." /></div></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="relative overflow-hidden rounded-[2.5rem] bg-[#f0c85e] px-7 py-12 sm:px-14 lg:flex lg:items-center lg:justify-between lg:py-16"><BookOpen className="absolute -bottom-10 -right-6 size-52 text-[#123f59]/10" strokeWidth={1}/><div className="relative max-w-2xl"><p className="text-xs font-black uppercase tracking-[.22em] text-[#76530c]">Um módulo da C.E.L.C</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Livraria Humberto de Campos</h2><p className="mt-5 text-lg leading-8 text-[#5e531f]">Conhecimento para iluminar a jornada. Acesse o acervo e a gestão da livraria da nossa casa.</p></div><Link href="/produtos" className="relative mt-8 inline-flex shrink-0 items-center gap-3 rounded-full bg-[#123f59] px-7 py-4 font-bold text-white hover:-translate-y-0.5 lg:mt-0">Acessar livraria <ArrowRight className="size-4" /></Link></div></div></section>
    </main>

    <footer id="contato" className="bg-[#062f48] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1.2fr_1fr_1fr] lg:py-20"><div><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-white"><Image src="/celc-logo.png" alt="" width={27} height={41}/></span><div><strong className="font-serif text-xl tracking-[.13em]">C.E.L.C</strong><p className="text-xs text-white/55">Casa Espiritualista Luz do Caminho</p></div></div><p className="mt-6 max-w-md leading-7 text-white/60">Uma comunidade de fé, estudo e caridade a serviço do desenvolvimento humano e espiritual.</p><div className="mt-7 flex gap-3"><Social href="https://www.instagram.com/celc1977/" label="Instagram" icon={Instagram}/><Social href="https://www.facebook.com/celc1977" label="Facebook" icon={Facebook}/><Social href="https://www.youtube.com/channel/UCbv1TqmUg9au-PHnRfDJdyA" label="YouTube" icon={Youtube}/></div></div><div><h3 className="footer-title">Onde estamos</h3><p className="mt-5 leading-7 text-white/70">Rua Araguaia, Quadra 12<br/>Lotes 1 e 20, Jardim Flamboyant<br/>Luziânia — GO, CEP 72.852-565</p><p className="mt-4 flex items-center gap-2 text-sm text-white/55"><MapPin className="size-4"/>A 800m da UNIDESC</p></div><div><h3 className="footer-title">Fale conosco</h3><a href="https://wa.me/5561984785501" className="mt-5 flex items-center gap-3 text-lg font-semibold hover:text-[#f4ce6a]"><MessageCircle className="size-5"/>(61) 98478-5501</a><p className="mt-4 flex items-center gap-3 text-white/60"><Clock3 className="size-5"/>Atendimento aos domingos</p></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-6 text-xs text-white/40 sm:flex-row sm:justify-between sm:px-8"><p>© {new Date().getFullYear()} C.E.L.C. Todos os direitos reservados.</p><p>Casa Espiritualista Luz do Caminho</p></div></div></footer>
  </div>;
}

function Feature({icon: Icon,title,text}:{icon:typeof Users;title:string;text:string}) { return <div className="flex gap-5 rounded-3xl bg-white/70 p-6"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-[#f2cd68]/30"><Icon className="size-5 text-[#176256]"/></span><div><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#60767e]">{text}</p></div></div>; }
function Social({href,label,icon:Icon}:{href:string;label:string;icon:ComponentType<{className?:string}>}) { return <a href={href} aria-label={label} className="social-link"><Icon className="size-4"/></a>; }
function Facebook({className}:{className?:string}) { return <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M13.5 21v-8h2.8l.4-3h-3.2V8.1c0-.9.3-1.5 1.6-1.5h1.7V3.9c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3V10H7.3v3h2.8v8h3.4Z"/></svg>; }
function Instagram({className}:{className?:string}) { return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>; }
function Youtube({className}:{className?:string}) { return <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21.6 7.2a2.8 2.8 0 0 0-2-2C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.8 2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.8ZM10 15.2V8.8l5.5 3.2-5.5 3.2Z"/></svg>; }
