"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Eye, Plus, ReceiptText, ShoppingBag } from "lucide-react";
import { bookstoreService, localDate } from "../service";
import { dateTime, money, paymentLabels } from "../format";
import type { Sale } from "../types";
import { EmptyState, Metric, Modal, Notice, PageHeading, useBookstoreData } from "./shared";

const loadDashboard = async () => ({ products: await bookstoreService.products.list(), customers: await bookstoreService.customers.list(), sales: await bookstoreService.sales.list() });
export function SalesPage({ overview = false }: { overview?: boolean }) {
  const { data, error } = useBookstoreData(loadDashboard);
  const [selected, setSelected] = useState<Sale | null>(null);
  const [status, setStatus] = useState("");
  const [search, setSearch] = useState("");
  const sales = data?.sales ?? [];
  const todaySales = sales.filter((s) => localDate(new Date(s.createdAt)) === localDate());
  const filtered = sales.filter((s) => (!status || s.status === status) && `${s.number} ${s.customerName}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  const visible = overview ? filtered.slice(0, 5) : filtered;
  return <><PageHeading title={overview ? "Bem-vindo à livraria" : "Histórico de vendas"} description={overview ? "Um espaço de conhecimento, cuidado e bons encontros." : "Acompanhe cada venda e os pagamentos que estão por vir."} action={<Link className="book-button primary" href="/caixa"><Plus size={18}/> Nova venda</Link>}/>
    {overview && <section className="welcome-banner"><div><p className="book-eyebrow">CONHECIMENTO QUE TRANSFORMA</p><h2>Cada livro abre<br/>um novo caminho.</h2><p>O próximo encontro com uma boa leitura começa aqui.</p><Link href="/caixa">Abrir frente de caixa <ArrowRight size={17}/></Link></div><div className="banner-art" aria-hidden="true"><BookOpen size={126} strokeWidth={.7}/><span>HUMBERTO DE CAMPOS</span></div></section>}
    <div className="metric-grid three"><Metric label="Vendas de hoje" value={money(todaySales.reduce((sum, s) => sum + Math.round(s.total * 100), 0) / 100)} note={`${todaySales.length} vendas registradas hoje`} icon={<ShoppingBag size={21}/>}/><Metric label="Recebido hoje" value={money(todaySales.filter((s) => s.status === "paid").reduce((sum, s) => sum + Math.round(s.total * 100), 0) / 100)} note="Pix, cartões e dinheiro" icon={<ReceiptText size={21}/>}/><Metric label="A receber" value={money(sales.filter((s) => s.status === "pending").reduce((sum, s) => sum + Math.round(s.total * 100), 0) / 100)} note={`${sales.filter((s) => s.status === "pending").length} vendas a prazo pendentes`} warm/></div>
    {error && <Notice>{error}</Notice>}<section className="book-panel"><div className="panel-heading"><div><h2>{overview ? "Últimas vendas" : "Todas as vendas"}</h2><p>{overview ? "Os últimos encontros da livraria, em um só lugar." : "Abra uma venda para consultar produtos, valores e pagamento."}</p></div>{overview ? <Link className="small-link" href="/vendas">Ver todas <ArrowRight size={15}/></Link> : <span className="count-badge">{visible.length} vendas</span>}</div>{!overview && <div className="table-toolbar"><input aria-label="Buscar venda" placeholder="Buscar por número ou cliente…" value={search} onChange={(e) => setSearch(e.target.value)}/><select aria-label="Filtrar pagamento" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos os pagamentos</option><option value="paid">Pagos</option><option value="pending">A prazo · pendentes</option></select></div>}
    {!data ? <div className="loading-state">Carregando vendas…</div> : !visible.length ? <EmptyState title={sales.length ? "Nenhuma venda encontrada" : "Sua próxima venda começa aqui"} description={sales.length ? "Altere a busca ou o filtro de pagamento." : "As vendas realizadas no caixa aparecerão nesta lista."}/> : <div className="table-scroll"><table className="book-table"><thead><tr><th>Venda / data</th><th>Cliente</th><th>Pagamento</th><th>Total</th><th>Situação</th><th><span className="sr-only">Detalhes</span></th></tr></thead><tbody>{visible.map((sale) => <tr key={sale.id}><td><strong>#{sale.number}</strong><small className="cell-secondary">{dateTime(sale.createdAt)}</small></td><td>{sale.customerName}</td><td>{paymentLabels[sale.payment.method]}</td><td><strong>{money(sale.total)}</strong></td><td><span className={`stock-tag ${sale.status === "pending" ? "low" : ""}`}><span/>{sale.status === "pending" ? "A receber" : "Pago"}</span></td><td><button className="icon-button" aria-label={`Detalhes da venda ${sale.number}`} onClick={() => setSelected(sale)}><Eye size={18}/></button></td></tr>)}</tbody></table></div>}</section>
    {overview && <div className="overview-links"><Link href="/produtos"><BookOpen size={22}/><div><strong>Cuidar do acervo</strong><span>{data?.products.length ?? 0} produtos cadastrados</span></div><ArrowRight size={18}/></Link><Link href="/clientes"><ShoppingBag size={22}/><div><strong>Conhecer nossos leitores</strong><span>{data?.customers.length ?? 0} clientes cadastrados</span></div><ArrowRight size={18}/></Link></div>}
    {selected && <Modal title={`Venda #${selected.number}`} description={dateTime(selected.createdAt)} onClose={() => setSelected(null)}><SaleReceipt sale={selected}/><div className="dialog-actions"><button className="book-button primary" onClick={() => setSelected(null)}>Fechar detalhes</button></div></Modal>}
  </>;
}
export function SaleReceipt({ sale }: { sale: Sale }) { return <div className="sale-receipt"><div className="receipt-customer"><small>CLIENTE</small><strong>{sale.customerName}</strong></div><div className="receipt-items">{sale.items.map((item) => <div key={item.productId}><div><strong>{item.name}</strong><small>{item.quantity} × {money(item.unitPrice)}</small></div><strong>{money(item.total)}</strong></div>)}</div><div className="receipt-total"><span>Total</span><strong>{money(sale.total)}</strong></div><div className="summary-line"><span>Pagamento</span><strong>{paymentLabels[sale.payment.method]}</strong></div>{sale.payment.method === "cash" && <><div className="summary-line"><span>Recebido</span><strong>{money(sale.payment.amountTendered ?? 0)}</strong></div><div className="summary-line"><span>Troco</span><strong>{money(sale.change)}</strong></div></>}{sale.payment.dueDate && <div className="summary-line"><span>Vencimento</span><strong>{sale.payment.dueDate.split("-").reverse().join("/")}</strong></div>}<p className={`receipt-status ${sale.status}`} >{sale.status === "pending" ? "A receber · pagamento a prazo" : "Pago · recebimento confirmado"}</p><p className="checkout-note">Registro de demonstração · sem valor fiscal</p></div>; }
